def test_function():
    def inner_function():
        print("Inner function in the field of test_function")
    inner_function()

test_function()
#inner_function() will be error. Very similar to encapsulation in the OOP.